

class TransactionPool:
    def __init__(self):
        self.transaction_map = {}

    def set_transaction(self, transaction):
        """
        Will set a transaction in a transaction pool.
        """
        self.transaction_map[transaction.id] = transaction

    def existing_transaction(self, address):
        """
        Will find a transaction generated by the given address in the transaction pool.
        """
        for transaction in self.transaction_map.values():
            if transaction.input['address'] == address: return transaction
